// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete() {
  return window['go']['main']['Complement']['Delete']();
}

export function GetValueData() {
  return window['go']['main']['Complement']['GetValueData']();
}

export function Pop() {
  return window['go']['main']['Complement']['Pop']();
}

export function Push(arg1) {
  return window['go']['main']['Complement']['Push'](arg1);
}
