// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetValueData():Promise<main.ValueData>;

export function Pop():Promise<void>;

export function Push(arg1:number):Promise<void>;
